export const products = [
    {
        id: '1001',
        index: '1',
        name: 'Mystic Tome of Elders',
        category: 'Books',
        img: 'img/mystic-tome.jpg',
        price: '19.99',
        description: 'A captivating book filled with ancient wisdom and spells, perfect for any fantasy lover.',
    },
    {
        id: '1002',
        index: '2',
        name: 'Dungeon Master’s Screen',
        category: 'Tabletop Games',
        img: 'img/dm-screen.jpg',
        price: '14.99',
        description: 'A sturdy screen with essential tables and rules for Dungeon Masters.',
    },
    {
        id: '1003',
        index: '3',
        name: 'Dragon Dice Set',
        category: 'Tabletop Games',
        img: 'img/dragon-dice.jpg',
        price: '9.99',
        description: 'A set of beautifully crafted dice with a dragon-themed design, perfect for any role-playing game.',
    },
    {
        id: '1004',
        index: '4',
        name: 'Collector’s Edition Map of Middle-Earth',
        category: 'Merchandise',
        img: 'img/middle-earth-map.jpg',
        price: '29.99',
        description: 'A detailed and framed map of Middle-Earth, perfect for fans of Tolkien’s work.',
    },
    {
        id: '1005',
        index: '5',
        name: 'Gothic Horror Anthology',
        category: 'Books',
        img: 'img/gothic-horror.jpg',
        price: '24.99',
        description: 'A collection of the best gothic horror stories from the 19th century.',
    },
    {
        id: '1006',
        index: '6',
        name: 'Elven Cloak Replica',
        category: 'Merchandise',
        img: 'img/elven-cloak.jpg',
        price: '49.99',
        description: 'A high-quality replica of the Elven cloak worn by characters in fantasy novels.',
    },
    {
        id: '1007',
        index: '7',
        name: 'Board Game: Quest for the Crown',
        category: 'Tabletop Games',
        img: 'img/quest-crown.jpg',
        price: '39.99',
        description: 'An epic adventure board game where players compete to claim the throne.',
    },
    {
        id: '1008',
        index: '8',
        name: 'Enchanted Forest Puzzle',
        category: 'Merchandise',
        img: 'img/forest-puzzle.jpg',
        price: '12.99',
        description: 'A 1000-piece puzzle featuring a beautifully illustrated enchanted forest.',
    },
    {
        id: '1009',
        index: '9',
        name: 'Arcane Grimoire',
        category: 'Books',
        img: 'img/arcane-grimoire.jpg',
        price: '34.99',
        description: 'A mystical book filled with arcane knowledge and forgotten spells.',
    },
    {
        id: '1010',
        index: '10',
        name: 'Tavern Mug Set',
        category: 'Merchandise',
        img: 'img/tavern-mug.jpg',
        price: '24.99',
        description: 'A set of two rustic mugs, perfect for enjoying a drink during game night.',
    },
    {
        id: '1011',
        index: '11',
        name: 'Rogue’s Handbook',
        category: 'Books',
        img: 'img/rogue-handbook.jpg',
        price: '19.99',
        description: 'A comprehensive guide for playing a rogue in tabletop role-playing games.',
    },
    {
        id: '1012',
        index: '12',
        name: 'Warrior’s Miniature Set',
        category: 'Tabletop Games',
        img: 'img/warrior-miniatures.jpg',
        price: '29.99',
        description: 'A set of highly detailed miniatures depicting various fantasy warriors.',
    },
    {
        id: '1013',
        index: '13',
        name: 'Elven Script Notebook',
        category: 'Merchandise',
        img: 'img/elven-notebook.jpg',
        price: '14.99',
        description: 'A notebook adorned with elegant Elven script, ideal for jotting down spells or adventures.',
    },
    {
        id: '1014',
        index: '14',
        name: 'Sorcerer’s Spellbook',
        category: 'Books',
        img: 'img/sorcerer-spellbook.jpg',
        price: '22.99',
        description: 'A spellbook containing powerful incantations and magical lore.',
    },
    {
        id: '1015',
        index: '15',
        name: 'Knight’s Armor Hoodie',
        category: 'Merchandise',
        img: 'img/knight-hoodie.jpg',
        price: '34.99',
        description: 'A comfortable hoodie designed to look like a knight’s armor, perfect for cosplaying.',
    },
    {
        id: '1016',
        index: '16',
        name: 'Witch’s Brew Candle',
        category: 'Merchandise',
        img: 'img/witch-candle.jpg',
        price: '9.99',
        description: 'A scented candle with a bewitching aroma, perfect for setting a mystical atmosphere.',
    },
    {
        id: '1017',
        index: '17',
        name: 'Grimoire Bookmark Set',
        category: 'Merchandise',
        img: 'img/grimoire-bookmarks.jpg',
        price: '7.99',
        description: 'A set of bookmarks inspired by ancient grimoires, ideal for keeping your place in any book.',
    },
    {
        id: '1018',
        index: '18',
        name: 'Sorcery Strategy Game',
        category: 'Tabletop Games',
        img: 'img/sorcery-game.jpg',
        price: '44.99',
        description: 'A strategic board game where players master different schools of magic to dominate the battlefield.',
    },
    {
        id: '1019',
        index: '19',
        name: 'Giant’s Mead Stein',
        category: 'Merchandise',
        img: 'img/giant-stein.jpg',
        price: '19.99',
        description: 'A large stein perfect for enjoying a hearty drink after a day of adventuring.',
    },
    {
        id: '1020',
        index: '20',
        name: 'Dark Tower Campaign',
        category: 'Tabletop Games',
        img: 'img/dark-tower.jpg',
        price: '49.99',
        description: 'An immersive campaign module for tabletop RPGs, filled with challenges and lore.',
    },
];
